name: Continuous Delivery

on:
  push:
    branches: "main"

env:
  IMAGE_NAME: environment-alert-api-dev
  AZURE_WEBAPP_NAME: environment-alert-api-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_NAME }}/environment-alert:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'environment-alert-api-dev'
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: 'ghcr.io/${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.IMAGE_NAME }}:latest'
