name: continuous_integration

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java Application
        run: mvn clean package
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          MAVEN_OPTS: "-Xmx1024m -XX:MaxPermSize=256m"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_NAME }}/environment-alert:latest

      - name: Verify Image Push
        run: |
          echo "Verifying if image was pushed successfully..."
          docker pull ${{ secrets.DOCKERHUB_USER_NAME }}/environment-alert:latest
          docker images
