on:
  push:
    branches: "main"

env:
  IMAGE_NAME: environment-alert
  AZURE_WEBAPP_NAME: api-environment-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4

      -   name: Setup Java SDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.IMAGE_NAME }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ secrets.DOCKERHUB_USER_NAME }}/${{ env.IMAGE_NAME }}:latest'